export const ErrorCodes = {
    // Standard HTTP Error Categories
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    DUPLICATE_KEY_ERROR: 'DUPLICATE_KEY_ERROR',
    INVALID_ID: 'INVALID_ID',

    // Domain Specific: Auth
    AUTH_NO_TOKEN: 'AUTH_NO_TOKEN',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
    AUTH_USER_DELETED: 'AUTH_USER_DELETED',
    AUTH_ACCOUNT_DELETED: 'AUTH_ACCOUNT_DELETED',
    AUTH_ACCOUNT_NOT_VERIFIED: 'AUTH_ACCOUNT_NOT_VERIFIED',
    AUTH_ACCOUNT_BLOCKED: 'AUTH_ACCOUNT_BLOCKED',
    AUTH_REQUIRED: 'AUTH_REQUIRED',
    AUTH_WRONG_PASSWORD: 'AUTH_WRONG_PASSWORD',
    AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

    // Domain Specific: KYC & User/Organizer
    KYC_REQUIRED: 'KYC_REQUIRED',
    KYC_NOT_APPROVED: 'KYC_NOT_APPROVED',
    KYC_SUBMISSION_EXISTS: 'KYC_SUBMISSION_EXISTS',
    KYC_NOT_SUBMITTED: 'KYC_NOT_SUBMITTED',
    ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
    ALREADY_APPLIED: 'ALREADY_APPLIED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_STATE: 'INVALID_STATE',

    // Domain Specific: ChitCycle / Auction / Bid
    CYCLE_NOT_FOUND: 'CYCLE_NOT_FOUND',
    CYCLE_ALREADY_EXISTS: 'CYCLE_ALREADY_EXISTS',
    INVALID_CYCLE_STATE: 'INVALID_CYCLE_STATE',
    WINNER_NOT_DECLARED: 'WINNER_NOT_DECLARED',
    AUCTION_NOT_ACTIVE: 'AUCTION_NOT_ACTIVE',
    BID_TOO_LOW: 'BID_TOO_LOW',
    BID_WINDOW_CLOSED: 'BID_WINDOW_CLOSED',

    // Domain Specific: Collection & Payment
    COLLECTIONS_ALREADY_OPEN: 'COLLECTIONS_ALREADY_OPEN',
    COLLECTIONS_CLOSED: 'COLLECTIONS_CLOSED',
    COLLECTIONS_NOT_STARTED: 'COLLECTIONS_NOT_STARTED',
    COLLECTIONS_ALREADY_CLOSED: 'COLLECTIONS_ALREADY_CLOSED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
    INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
    DUPLICATE_PAYMENT: 'DUPLICATE_PAYMENT',

    // Domain Specific: Installment
    INSTALLMENT_NOT_FOUND: 'INSTALLMENT_NOT_FOUND',
    NO_ACTIVE_MEMBERS: 'NO_ACTIVE_MEMBERS',
    INSTALLMENT_ALREADY_PAID: 'INSTALLMENT_ALREADY_PAID',

    // Domain Specific: Ledger & Statement
    INVALID_AMOUNT: 'INVALID_AMOUNT',
    INVALID_MEMBER_ID: 'INVALID_MEMBER_ID',
    INVALID_ORGANIZER_ID: 'INVALID_ORGANIZER_ID',
    INVALID_GROUP_ID: 'INVALID_GROUP_ID',
    MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
    ORGANIZER_NOT_FOUND: 'ORGANIZER_NOT_FOUND',
    GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',

    // External Services
    CLOUDINARY_ERROR: 'CLOUDINARY_ERROR',
    CLOUDINARY_CONFIG_ERROR: 'CLOUDINARY_CONFIG_ERROR'
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes] | string;
